name: Deploy

on:
  push:
    branches: [main]

jobs:
  replace-secrets:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Replace GitHub Token
      run: |
        # Reemplazar solo el token manteniendo el formato
        sed -i "s/ghp_placeholder/${{ secrets.GH_TOKEN }}/g" admin.js
        
        # Verificar cambios (opcional)
        grep "const GITHUB_TOKEN" admin.js
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GH_TOKEN }}
        publish_dir: ./
